[versions]
android = "8.1.1"
kotlin = "1.8.10"
ktx = "1.10.1"
appcompat = "1.6.1"
material = "1.9.0"
constraintlayout = "2.1.4"
junit = "4.13.2"
androidx_junit = "1.1.5"
espresso = "3.5.1"
serialization = "1.5.1"
room = "2.5.2"
navigation = "2.7.0"
fragment = "1.6.1"
retrofit = "2.9.0"
interceptor = "4.10.0"
glide = "4.14.2"
dagger = "2.46.1"
coroutines = "1.7.3"
ksp = "1.8.10-1.0.9"
kotlinx_retrofit = "1.0.0"
nav_safe_args = "2.5.3"


[libraries]
android-gradle-plugin = { module = "com.android.tools.build:gradle",             version.ref = "android" }
kotlin-gradle-plugin =  { module = "org.jetbrains.kotlin:kotlin-gradle-plugin",  version.ref = "kotlin" }
core-ktx =              { module = "androidx.core:core-ktx",                     version.ref = "ktx" }
appcompat =             { module = "androidx.appcompat:appcompat",               version.ref = "appcompat" }
material =              { module = "com.google.android.material:material",       version.ref = "material" }
constraintlayout =      { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
junit =                 { module = "junit:junit",                                version.ref = "junit" }
androidx-junit =        { module = "androidx.test.ext:junit",                    version.ref = "androidx_junit" }
test-espresso-core =    { module = "androidx.test.espresso:espresso-core",       version.ref = "espresso" }

# Kotlinx.Serialization
serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
kotlin-stdlib =      { module = "org.jetbrains.kotlin:kotlin-stdlib",               version.ref = "kotlin" }
kotlinx-retrofit=   { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "kotlinx_retrofit" }

# Room
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-runtime =  { module = "androidx.room:room-runtime",  version.ref = "room" }
room-ktx =      { module = "androidx.room:room-ktx",      version.ref = "room" }

# Jetpack Navigation Component
navigation-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
navigation-ui =       { module = "androidx.navigation:navigation-ui-ktx",       version.ref = "navigation" }
fragment =            { module = "androidx.fragment:fragment-ktx",              version.ref = "fragment" }

# Retrofit + converter JSON/JAVA + Intercepter
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "interceptor" }
converter-gson =      { module = "com.squareup.retrofit2:converter-gson",    version.ref = "retrofit" }
retrofit =            { module = "com.squareup.retrofit2:retrofit",          version.ref = "retrofit" }

# Glide: show images from network
glide-compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }
glide =          { module = "com.github.bumptech.glide:glide",    version.ref = "glide" }

# Dagger
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }
dagger =          { module = "com.google.dagger:dagger",          version.ref = "dagger" }

# Coroutines
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-core =    { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core",    version.ref = "coroutines" }



[bundles]
navigation-component = ["navigation-fragment", "navigation-ui", "fragment"]
serialization =        ["kotlin-stdlib", "serialization-json"]
retrofit2 =            ["retrofit", "converter-gson", "logging-interceptor"]
room =                 ["room-runtime", "room-ktx"]


[plugins]
android-application =  { id = "com.android.application", version.ref = "android" }
android-library =      { id = "com.android.library",     version.ref = "android" }

kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-android =       { id = "org.jetbrains.kotlin.android",              version.ref = "kotlin"  }
ksp =                  { id = "com.google.devtools.ksp",                   version.ref = "ksp"}
kapt =                 { id = "org.jetbrains.kotlin.kapt",                 version.ref = "kotlin"}
safe-args =            { id = "androidx.navigation.safeargs",              version.ref = "nav_safe_args"}