[versions]
android = "8.1.1"
kotlin = "1.8.10"
ksp = "1.8.10-1.0.9"
ksjson = "1.5.1"
room = "2.5.2"
navigation = "2.7.0"
fragmnt = "1.6.1"
retroft = "2.9.0"
intercpt = "4.10.0"
gld = "4.14.2"
daggr = "2.46.1"
kn = "3.3.0"
coroutns = "1.7.0"


[libraries]
android-gradle-plugin = { module = "com.android.tools.build:gradle",            version.ref = "android" }
kotlin-gradle-plugin =  { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

# Kotlinx.Serialization
serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "ksjson" }
kotlin-stdlib =      { module = "org.jetbrains.kotlin:kotlin-stdlib",               version.ref = "kotlin" }

# Room
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-runtime =  { module = "androidx.room:room-runtime",  version.ref = "room" }
room-ktx =      { module = "androidx.room:room-ktx",      version.ref = "room" }

# Jetpack Navigation Component
navigation-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
navigation-ui =       { module = "androidx.navigation:navigation-ui-ktx",       version.ref = "navigation" }
fragment =            { module = "androidx.fragment:fragment-ktx",              version.ref = "fragmnt" }

# Retrofit + converter JSON/JAVA + Intercepter
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "intercpt" }
converter-gson =      { module = "com.squareup.retrofit2:converter-gson",    version.ref = "retroft" }
retrofit =            { module = "com.squareup.retrofit2:retrofit",          version.ref = "retroft" }

# Glide: show images from network
glide-compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "gld" }
glide =          { module = "com.github.bumptech.glide:glide",    version.ref = "gld" }

# Dagger
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "daggr" }
dagger =          { module = "com.google.dagger:dagger",          version.ref = "daggr" }

# Coroutines
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutns" }


[bundles]
navigation-component = ["navigation-fragment", "navigation-ui", "fragment"]
serialization =        ["kotlin-stdlib", "serialization-json"]
retrofit2 =            ["retrofit", "converter-gson", "logging-interceptor"]
room =                 ["room-runtime", "room-ktx"]


[plugins]
android-application =  { id = "com.android.application", version.ref = "android" }
android-library =      { id = "com.android.library",     version.ref = "android" }

kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-android =       { id = "org.jetbrains.kotlin.android",              version.ref = "kotlin"  }
ksp =                  { id = "com.google.devtools.ksp",                   version.ref = "ksp"}